FROM node:14

WORKDIR /app

COPY ./chess-data-stream-processor/primary-stream ./chess-data-stream-processor/primary-stream
COPY ./src/artifacts/contracts/ChessWager.sol/ChessWager.json ./src/artifacts/contracts/ChessWager.sol/ChessWager.json

COPY .env ./

COPY ./chess-data-stream-processor/payment-processor ./chess-data-stream-processor/payment-processor

WORKDIR /app/chess-data-stream-processor/payment-processor
RUN npm install

WORKDIR /app/chess-data-stream-processor/primary-stream

RUN npm install

CMD ["bash", "./start.sh"]
