FROM node:18

WORKDIR /app

COPY ./contract-listener ./contract-listener

COPY ./src/artifacts/contracts/ChessWager.sol/ChessWager.json ./src/artifacts/contracts/ChessWager.sol/ChessWager.json

COPY .env ./

WORKDIR /app/contract-listener/

RUN npm install

CMD ["npm", "start"]