FROM node:14

WORKDIR /app

COPY ./chess-data-stream-processor/ancillary-stream ./chess-data-stream-processor/ancillary-stream
COPY ./src/artifacts/contracts/ChessWager.sol/ChessWager.json ./src/artifacts/contracts/ChessWager.sol/ChessWager.json

# only in local
# COPY ./chess-wager-develop-firebase-adminsdk-z02bi-9bab414c8a.json ./

COPY .env ./

WORKDIR /app/chess-data-stream-processor/ancillary-stream

RUN npm install

CMD ["bash", "./start.sh"]

