# specifically for backend, but need .env
FROM node:14

WORKDIR /app

COPY ./chess-data-stream-processor/primary-stream ./chess-data-stream-processor/primary-stream
COPY ./src/artifacts/contracts/ChessWager.sol/ChessWager.json ./src/artifacts/contracts/ChessWager.sol/ChessWager.json

# only in local
COPY ./chess-wager-develop-firebase-adminsdk-z02bi-9bab414c8a.json ./

COPY .env ./

WORKDIR /app/chess-data-stream-processor/primary-stream

RUN npm install

CMD ["bash", "./start.sh"]

# CMD [ "npm", "start"]
