FROM node:18

WORKDIR /app

COPY ./contract-listener ./contract-listener

COPY ./src/artifacts/contracts/ChessWager.sol/ChessWager.json ./src/artifacts/contracts/ChessWager.sol/ChessWager.json

# only in local
COPY ./chess-wager-develop-firebase-adminsdk-z02bi-dfa580a7a5.json ./
COPY ./chess-wager-main-firebase-adminsdk-bgzkv-ae51fbde5c.json ./

COPY .env ./

WORKDIR /app/contract-listener/

RUN npm install

CMD ["npm", "start"]