FROM node:14

WORKDIR /app

COPY ./chess-data-stream-processor/primary-stream ./chess-data-stream-processor/primary-stream
COPY ./src/artifacts/contracts/ChessWager.sol/ChessWager.json ./src/artifacts/contracts/ChessWager.sol/ChessWager.json

# only in local
COPY ./chess-wager-develop-firebase-adminsdk-z02bi-dfa580a7a5.json ./
# COPY ./chess-wager-main-firebase-adminsdk-bgzkv-ae51fbde5c.json ./

COPY .env ./

COPY ./chess-data-stream-processor/payment-processor ./chess-data-stream-processor/payment-processor

WORKDIR /app/chess-data-stream-processor/payment-processor
RUN npm install

WORKDIR /app/chess-data-stream-processor/primary-stream

RUN npm install

CMD ["npm", "start"]
