steps:
  - id: Decrypting environment variables
    name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=env/.env.$BRANCH_NAME.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=chess-wager
      - --key=chess-wager-$BRANCH_NAME
  - id: Installing dependencies for frontend
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "--no-optional", "-f"]
  - id: Installing firebase tools
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "-g", "firebase-tools"]
  - id: Installing firebase
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "--save", "firebase"]

  # - id: Running tests
  #   name: "gcr.io/cloud-builders/npm"
  #   args: ["run", "test", "--", "--watchAll=false"]

  - id: Building frontend
    name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  - id: Selecting firebase env
    name: "gcr.io/$PROJECT_ID/firebase"
    args: ["use", "$BRANCH_NAME"]
  - id: Deploying to firebase
    name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--only", "hosting", "--project=$PROJECT_ID"]

timeout: 3600s
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _IMAGE_NAME_AS: >-
    gcr.io/chess-wager-${BRANCH_NAME}/github.com/geektechniquestudios/chesswager/ancillary-stream
  _DOCKERFILE_NAME_AS: >-
    Dockerfile.ancillary-stream-processor
  _IMAGE_NAME_PS: >-
    gcr.io/chess-wager-${BRANCH_NAME}/github.com/geektechniquestudios/chesswager/primary-stream
  _DOCKERFILE_NAME_PS: >-
    Dockerfile.primary-stream-processor
  _IMAGE_NAME_CL: >-
    gcr.io/chess-wager-${BRANCH_NAME}/github.com/geektechniquestudios/chesswager/contract-listener
  _DOCKERFILE_NAME_CL: >-
    Dockerfile.contract-listener
  _DOCKERFILE_DIR: ""
  _GKE_CLUSTER: chess-wager-${BRANCH_NAME}-env
  _K8S_NAMESPACE: default
  _K8S_LABELS: ""
  _K8S_ANNOTATIONS: gcb-trigger-id=db343b67-9c4a-40ba-9650-43f1c5fc1809
  _K8S_YAML_PATH: kubernetes
  _K8S_APP_NAME: chess-wager-${BRANCH_NAME}-env
  _OUTPUT_BUCKET_PATH: chess-wager-${BRANCH_NAME}_cloudbuild/deploy
  _GKE_LOCATION: us-central1-a
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
