steps:
  - id: Decrypting environment variables
    name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=env/.env.$BRANCH_NAME.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=chess-wager
      - --key=chess-wager-$BRANCH_NAME

  # Build docker images for k8s
  - id: Building contract listener
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_IMAGE_NAME_CL:$COMMIT_SHA"
      - .
      - "-f"
      - $_DOCKERFILE_NAME_CL
    dir: $_DOCKERFILE_DIR
  - id: Building ancillary stream
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_IMAGE_NAME_AS:$COMMIT_SHA"
      - .
      - "-f"
      - $_DOCKERFILE_NAME_AS
    dir: $_DOCKERFILE_DIR
  - id: Building primary stream
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_IMAGE_NAME_PS:$COMMIT_SHA"
      - .
      - "-f"
      - $_DOCKERFILE_NAME_PS
    dir: $_DOCKERFILE_DIR
  - id: Building tertiary stream
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_IMAGE_NAME_TS:$COMMIT_SHA"
      - .
      - "-f"
      - $_DOCKERFILE_NAME_TS
    dir: $_DOCKERFILE_DIR

  # Pushing images
  - id: Pushing contract listener
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_IMAGE_NAME_CL:$COMMIT_SHA"
  - id: Pushing ancillary stream
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_IMAGE_NAME_AS:$COMMIT_SHA"
  - id: Pushing primary stream
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_IMAGE_NAME_PS:$COMMIT_SHA"
  - id: Pushing tertiary stream
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_IMAGE_NAME_TS:$COMMIT_SHA"

  # Deploying to k8s
  - id: Applying Redis server to k8s
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - "--filename=kubernetes/redis-deployment.yaml"
      - "--cluster=$_GKE_CLUSTER"
      - "--location=$_GKE_LOCATION"
      - "--namespace=$_K8S_NAMESPACE"
  - id: Clearing build folder from Redis
    name: bash
    args:
      - rm
      - "-rf"
      - output
  - id: Applying contract listener to k8s
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - "--filename=kubernetes/$BRANCH_NAME/contract-listener-deployment.yaml"
      - "--image=$_IMAGE_NAME_CL:$COMMIT_SHA"
      - "--cluster=$_GKE_CLUSTER"
      - "--location=$_GKE_LOCATION"
      - "--namespace=$_K8S_NAMESPACE"
      - "--timeout=10m"
  - id: Clearing build folder from contract listener
    name: bash
    args:
      - rm
      - "-rf"
      - output
  - id: Applying ancillary stream to k8s
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - "--filename=kubernetes/$BRANCH_NAME/ancillary-stream-deployment.yaml"
      - "--image=$_IMAGE_NAME_AS:$COMMIT_SHA"
      - "--cluster=$_GKE_CLUSTER"
      - "--location=$_GKE_LOCATION"
      - "--namespace=$_K8S_NAMESPACE"
      - "--timeout=10m"
  - id: Clearing build folder from ancillary stream
    name: bash
    args:
      - rm
      - "-rf"
      - output
  - id: Applying primary stream to k8s
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - "--filename=kubernetes/$BRANCH_NAME/primary-stream-deployment.yaml"
      - "--image=$_IMAGE_NAME_PS:$COMMIT_SHA"
      - "--cluster=$_GKE_CLUSTER"
      - "--location=$_GKE_LOCATION"
      - "--namespace=$_K8S_NAMESPACE"
      - "--timeout=10m"
  - id: Clearing build folder from primary stream
    name: bash
    args:
      - rm
      - "-rf"
      - output
  - id: Applying tertiary stream to k8s
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - "--filename=kubernetes/$BRANCH_NAME/tertiary-stream-deployment.yaml"
      - "--image=$_IMAGE_NAME_TS:$COMMIT_SHA"
      - "--cluster=$_GKE_CLUSTER"
      - "--location=$_GKE_LOCATION"
      - "--namespace=$_K8S_NAMESPACE"
      - "--timeout=10m"

timeout: 3600s
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _IMAGE_NAME_AS: >-
    gcr.io/chess-wager-${BRANCH_NAME}/github.com/geektechniquestudios/chesswager/ancillary-stream
  _DOCKERFILE_NAME_AS: >-
    Dockerfile.ancillary-stream-processor
  _IMAGE_NAME_PS: >-
    gcr.io/chess-wager-${BRANCH_NAME}/github.com/geektechniquestudios/chesswager/primary-stream
  _DOCKERFILE_NAME_PS: >-
    Dockerfile.primary-stream-processor
  _IMAGE_NAME_CL: >-
    gcr.io/chess-wager-${BRANCH_NAME}/github.com/geektechniquestudios/chesswager/contract-listener
  _DOCKERFILE_NAME_CL: >-
    Dockerfile.contract-listener
  _IMAGE_NAME_TS: >-
    gcr.io/chess-wager-${BRANCH_NAME}/github.com/geektechniquestudios/chesswager/tertiary-stream
  _DOCKERFILE_NAME_TS: >-
    Dockerfile.tertiary-stream
  _DOCKERFILE_DIR: ""
  _GKE_CLUSTER: chess-wager-${BRANCH_NAME}-env
  _K8S_NAMESPACE: default
  _K8S_LABELS: ""
  _K8S_ANNOTATIONS: gcb-trigger-id=db343b67-9c4a-40ba-9650-43f1c5fc1809
  _K8S_YAML_PATH: kubernetes
  _K8S_APP_NAME: chess-wager-${BRANCH_NAME}-env
  _OUTPUT_BUCKET_PATH: chess-wager-${BRANCH_NAME}_cloudbuild/deploy
  _GKE_LOCATION: us-central1-a
  _BRANCH_NAME: "$BRANCH_NAME"
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
