apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ancillary-stream
  name: ancillary-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ancillary-stream
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ancillary-stream
    spec:
      containers:
        - env:
          image: gcr.io/chess-wager-main/github.com/geektechniquestudios/chesswager/ancillary-stream
          livenessProbe:
            exec:
              command:
                - curl -sS http://127.0.0.1 || exit 1
            failureThreshold: 3
            periodSeconds: 90
            timeoutSeconds: 10
          name: ancillary-stream
          resources: {}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10m"]
      terminationGracePeriodSeconds: 360
      restartPolicy: Always
status: {}
