describe("betting lobby", () => {
  
  it("should allow logged in users to click on a bet, making it selected", () => {})
  // it("shouldn't allow unauthenticated users to click bets", () => {})
  // it("should keep selected bets in place as other bets move around", () => {})
  // it("should allow users to join", () => {})
  // it("should allow bet creator to delete own bet", () => {})
  // it("should allow bet creator to kick other user", () => {})
  // it("should allow bet creator to accept other user", () => {})
  // it("should open the persona menu if a user title is clicked", () => {})
  // it("should update user stats based on outcome", () => {})
  // it("should correctly sort bets based on each lobby header button", () => {})
  // it("should despawn funded bets", () => {})
  // it("should despawn deleted bets", () => {})
  // it("should allow user to pay", () => {})
})
