apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    io.kompose.service: stream-data
  name: stream-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
volumeBindingMode: Immediate
status: {}
